Creating a 1d array of size 5

In [ ]:
import numpy as np

array = np.array(range(5))

array

array([0, 1, 2, 3, 4])

Creating a 2d array of 10 elements

In [ ]:
array2d = np.array([range(5),range(5)])

array2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
array.shape

(5,)

Shape is represented in terms of (rows,columns) for 2d Arrays

Below tests are to highlight the basic properties of NumPy arrays which are 
  Shape(Size of arry for each dimension),Size(Number of elements),Ndim  (Dimensions) and DType(Data Type)

In [ ]:
array2d.shape

(2, 5)

In [ ]:
array.size

5

In [ ]:
array2d.size

10

In [ ]:
array.ndim

1

In [ ]:
array2d.ndim

2

In [ ]:
array.dtype

dtype('int64')

In [ ]:
array2d.dtype

dtype('int64')

# Arrays Creation

In [ ]:
# You can use the following alternatives t convering lists , so you can create arrays using functions:
"""
  a) ones- creates an array of ones of a given size,as float by default: np.ones((rows,cols),dtype)
  b) zeros- array of zeros of a given size, as float by default: np.zeros((rows,cols),dtype)
  c) arange- creates an array of integers with given start and stop values and a step size(Only stop is required,and is not inclusive): np.arange(start,stop,step)
  d) linspace- Creates an array of floats with given start and stop values with n elements,separated by a consistent step size(stop is inclusive): np.linspace(start,stop,n)
  e) reshape- Changes the array into the specified dimensions, if compatible: np.reshape(rows,cols)

"""
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(10,100,9).reshape(3,3)

array([[ 10.  ,  21.25,  32.5 ],
       [ 43.75,  55.  ,  66.25],
       [ 77.5 ,  88.75, 100.  ]])

# Random Number Arrays
You can create random number arrays from a variety of distributions using NUmPy functions and methods(great for sampling and simulations).
This can be achieved through the following methods:
* default_rng- Creates a random number generator (*seed* is for reproducibility): **np.default_rng(*seed*)**
* random- Returns *n* random numbers from a uniform distribution between 0 and 1: **rng.random(*n*)**
* normal- Returns *n* random numbers from a normal distribution with a given *mean* and *standard deviation*: **rng.normal(*mean,stdev,n*)**

*rng is the standard variable name for the default_rng number generator*

In [ ]:
from numpy.random import default_rng

In [ ]:
rng = default_rng(12345)

random_array = rng.random(10)
random_array

# 10 random numbers will be generated between 0 and 1.

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [ ]:
rng = np.random.default_rng(616)

rng.random(10)
rng.integers(0,10,200)

# 200 numbers will be generated between 0 and 10 which will be integers.

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5, 9, 8, 7, 5, 0, 5, 6, 9, 2, 1,
       1, 6, 8, 4, 7, 5, 8, 2, 8, 3, 3, 9, 6, 0, 1, 3, 1, 7, 5, 3, 7, 2,
       2, 4, 0, 7, 1, 1, 0, 6, 1, 2, 8, 7, 4, 6, 2, 3, 3, 0, 2, 2, 4, 8,
       0, 0, 4, 5, 8, 6, 8, 1, 3, 5, 5, 5, 7, 0, 0, 6, 9, 9, 0, 8, 5, 3,
       3, 6, 2, 6, 1, 3, 8, 6, 3, 2, 2, 5, 2, 6, 9, 2, 5, 0, 6, 1, 3, 1,
       9, 4])

In [ ]:
rng.normal(50,5,100)
# 100 random numbers will be generated from a pivot of 50 as mean and a standard deviation of 5

array([46.93674729, 59.54526862, 53.43774821, 48.43637794, 46.85678879,
       41.4561919 , 56.48790756, 53.94354469, 54.60078538, 48.61302076,
       46.30110108, 48.61251528, 46.39485879, 54.41308139, 51.5983339 ,
       55.19104088, 46.40247462, 49.2582163 , 50.96123011, 56.54043896,
       50.26802998, 49.4921062 , 58.75487245, 47.16539593, 46.75138407,
       53.34468975, 39.18803235, 48.46981803, 51.0826261 , 51.00021165,
       45.29226014, 48.8660567 , 50.85442464, 46.3814134 , 53.29796539,
       46.93488108, 52.76201276, 41.40470633, 49.54657275, 53.90543794,
       56.59157323, 50.28576144, 60.12955299, 55.25932041, 48.81370977,
       52.16739133, 53.62267161, 52.54240686, 47.27704318, 54.14478875,
       40.40326606, 49.53532289, 53.3934452 , 48.38581526, 49.86478599,
       44.38062247, 53.06039076, 47.40586151, 47.17316538, 43.53380576,
       49.58251427, 53.56075888, 52.99650921, 53.06638107, 54.85886533,
       47.45287589, 52.51216663, 45.73565211, 44.56405959, 41.77

# Indexing and Slicing Arrays

To access array elements, you need to either index or slice them

Indexing and slicing 1d arrays is the same as base python:
* **array[*index*]**- Indexes to access a single element.
* **array[*start:stop:step size*]**- Slicing to access a series of elements where stop is non-inclusive.






In [ ]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
integer_array[2]

2

In [ ]:
integer_array[-1]

11

In [ ]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [ ]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs','snacks','beverages','coffee','tea','spices'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [ ]:
product_array[1]

'vegetables'

In [ ]:
product_array[-1]

'spices'

In [ ]:
product_array[:5]

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
product_array[::-1]

array(['spices', 'tea', 'coffee', 'beverages', 'snacks', 'eggs', 'dairy',
       'cereal', 'vegetables', 'fruits'], dtype='<U10')

In [ ]:
product_array[5::2]

array(['snacks', 'coffee', 'spices'], dtype='<U10')

Indexing and slicing of 2d arrays requires an extra index or slice:
* **array[*row index:column index*]**- Indexing to access a single element.
* **array[*start:stop:step size, start:stop:step size*]**- Slicing to access a series of elements.

In [ ]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
new_array[:,3]

array([ 3,  7, 11])

In [ ]:
new_array[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
new_array[2,1]

9

In [ ]:
product_array2d = product_array.reshape(2,5)
product_array2d

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [ ]:
product_array2d[1,2] #Coffee is in the second row which means row index 1, and is in the third column which would be column index 2

'coffee'

In [ ]:
product_array2d[:,2:] #To grab all rows,and a portion of columns from the column index 2 to the end of column list, we supply a row index of : and column index of 2:

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U10')

In [ ]:
product_array2d[1,:] #Grabs a subset of rows and all columns

array(['snacks', 'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')