Creating a 1d array of size 5

In [1]:
import numpy as np

array = np.array(range(5))

array

array([0, 1, 2, 3, 4])

Creating a 2d array of 10 elements

In [2]:
array2d = np.array([range(5),range(5)])

array2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [3]:
array.shape

(5,)

Shape is represented in terms of (rows,columns) for 2d Arrays

Below tests are to highlight the basic properties of NumPy arrays which are 
  Shape(Size of arry for each dimension),Size(Number of elements),Ndim  (Dimensions) and DType(Data Type)

In [4]:
array2d.shape

(2, 5)

In [5]:
array.size

5

In [6]:
array2d.size

10

In [7]:
array.ndim

1

In [8]:
array2d.ndim

2

In [9]:
array.dtype

dtype('int64')

In [10]:
array2d.dtype

dtype('int64')

# Arrays Creation

In [11]:
# You can use the following alternatives t convering lists , so you can create arrays using functions:
"""
  a) ones- creates an array of ones of a given size,as float by default: np.ones((rows,cols),dtype)
  b) zeros- array of zeros of a given size, as float by default: np.zeros((rows,cols),dtype)
  c) arange- creates an array of integers with given start and stop values and a step size(Only stop is required,and is not inclusive): np.arange(start,stop,step)
  d) linspace- Creates an array of floats with given start and stop values with n elements,separated by a consistent step size(stop is inclusive): np.linspace(start,stop,n)
  e) reshape- Changes the array into the specified dimensions, if compatible: np.reshape(rows,cols)

"""
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
np.linspace(10,100,9).reshape(3,3)

array([[ 10.  ,  21.25,  32.5 ],
       [ 43.75,  55.  ,  66.25],
       [ 77.5 ,  88.75, 100.  ]])

# Random Number Arrays
You can create random number arrays from a variety of distributions using NUmPy functions and methods(great for sampling and simulations).
This can be achieved through the following methods:
* default_rng- Creates a random number generator (*seed* is for reproducibility): **np.default_rng(*seed*)**
* random- Returns *n* random numbers from a uniform distribution between 0 and 1: **rng.random(*n*)**
* normal- Returns *n* random numbers from a normal distribution with a given *mean* and *standard deviation*: **rng.normal(*mean,stdev,n*)**

*rng is the standard variable name for the default_rng number generator*

In [16]:
from numpy.random import default_rng

In [17]:
rng = default_rng(12345)

random_array = rng.random(10)
random_array

# 10 random numbers will be generated between 0 and 1.

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [18]:
rng = np.random.default_rng(616)

rng.random(10)
rng.integers(0,10,200)

# 200 numbers will be generated between 0 and 10 which will be integers.

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5, 9, 8, 7, 5, 0, 5, 6, 9, 2, 1,
       1, 6, 8, 4, 7, 5, 8, 2, 8, 3, 3, 9, 6, 0, 1, 3, 1, 7, 5, 3, 7, 2,
       2, 4, 0, 7, 1, 1, 0, 6, 1, 2, 8, 7, 4, 6, 2, 3, 3, 0, 2, 2, 4, 8,
       0, 0, 4, 5, 8, 6, 8, 1, 3, 5, 5, 5, 7, 0, 0, 6, 9, 9, 0, 8, 5, 3,
       3, 6, 2, 6, 1, 3, 8, 6, 3, 2, 2, 5, 2, 6, 9, 2, 5, 0, 6, 1, 3, 1,
       9, 4])

In [19]:
rng.normal(50,5,100)
# 100 random numbers will be generated from a pivot of 50 as mean and a standard deviation of 5

array([46.93674729, 59.54526862, 53.43774821, 48.43637794, 46.85678879,
       41.4561919 , 56.48790756, 53.94354469, 54.60078538, 48.61302076,
       46.30110108, 48.61251528, 46.39485879, 54.41308139, 51.5983339 ,
       55.19104088, 46.40247462, 49.2582163 , 50.96123011, 56.54043896,
       50.26802998, 49.4921062 , 58.75487245, 47.16539593, 46.75138407,
       53.34468975, 39.18803235, 48.46981803, 51.0826261 , 51.00021165,
       45.29226014, 48.8660567 , 50.85442464, 46.3814134 , 53.29796539,
       46.93488108, 52.76201276, 41.40470633, 49.54657275, 53.90543794,
       56.59157323, 50.28576144, 60.12955299, 55.25932041, 48.81370977,
       52.16739133, 53.62267161, 52.54240686, 47.27704318, 54.14478875,
       40.40326606, 49.53532289, 53.3934452 , 48.38581526, 49.86478599,
       44.38062247, 53.06039076, 47.40586151, 47.17316538, 43.53380576,
       49.58251427, 53.56075888, 52.99650921, 53.06638107, 54.85886533,
       47.45287589, 52.51216663, 45.73565211, 44.56405959, 41.77

# Indexing and Slicing Arrays

To access array elements, you need to either index or slice them

Indexing and slicing 1d arrays is the same as base python:
* **array[*index*]**- Indexes to access a single element.
* **array[*start:stop:step size*]**- Slicing to access a series of elements where stop is non-inclusive.






In [20]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
integer_array[2]

2

In [22]:
integer_array[-1]

11

In [23]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [24]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [25]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs','snacks','beverages','coffee','tea','spices'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [26]:
product_array[1]

'vegetables'

In [27]:
product_array[-1]

'spices'

In [28]:
product_array[:5]

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [29]:
product_array[::-1]

array(['spices', 'tea', 'coffee', 'beverages', 'snacks', 'eggs', 'dairy',
       'cereal', 'vegetables', 'fruits'], dtype='<U10')

In [30]:
product_array[5::2]

array(['snacks', 'coffee', 'spices'], dtype='<U10')

Indexing and slicing of 2d arrays requires an extra index or slice:
* **array[*row index:column index*]**- Indexing to access a single element.
* **array[*start:stop:step size, start:stop:step size*]**- Slicing to access a series of elements.

In [31]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
new_array[:,3]

array([ 3,  7, 11])

In [34]:
new_array[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [35]:
new_array[2,1]

9

In [36]:
product_array2d = product_array.reshape(2,5)
product_array2d

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [37]:
product_array2d[1,2] #Coffee is in the second row which means row index 1, and is in the third column which would be column index 2

'coffee'

In [38]:
product_array2d[:,2:] #To grab all rows,and a portion of columns from the column index 2 to the end of column list, we supply a row index of : and column index of 2:

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U10')

In [39]:
product_array2d[1,:] #Grabs a subset of rows and all columns

array(['snacks', 'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

# Filtering Arrays.

You can filter arrays by indexing them with a logical test, Only returning the elements in positions where the logical test returns True.



In [40]:
array = [[0,5,155,0,518],[0,1827,616,317,325]]

sales_array= np.array(array)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [41]:
# A logical test that returns a boolean value when the test runs against each element in the array.

sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [42]:
# Returns the values in the array that return True when the logical test is applied on them.

sales_array[sales_array != 0] 

array([   5,  155,  518, 1827,  616,  317,  325])

You can also filter arrays with multiple logical tests:
* Use **|** for **or** conditions and **&** for **and** conditions.


In [43]:
# Returning an array that returns element 616 or elements less than 100 from the array.

sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

In [44]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

You can keep your filters tidy by assigning them to variables and passing the variable to the array index like; 

In [45]:
mask = (sales_array > 100) & (sales_array < 500)

sales_array[mask]

array([155, 317, 325])

You can also filter arrays based on **Values in other arrays**.
 Use the boolean array returned from the other array to index the array you want to filter

In [46]:
product_array1 = product_array[:5]

product_array1

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [47]:
d_array = sales_array[:1].reshape(5)
d_array

array([  0,   5, 155,   0, 518])

In [48]:
# Indexing product_array1 with the indexes returned by d_arry greater than 0.
# The comparing arrays must be of the same dimension and size.
product_array1[d_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

You can modify array values by assigning new values.

You do this by specifying the index of the value you want to change and assign it a new value using the assignment operator.

In [49]:
d_array

array([  0,   5, 155,   0, 518])

In [50]:
# Assigns the value 10 as the new value to the d_array arrya index 1(The second item in the array).

d_array[1] = 10

d_array

array([  0,  10, 155,   0, 518])

In [51]:
# Assigns the value 25 to every index in the array where the value is zero.

d_array[d_array == 0] = 25
d_array

array([ 25,  10, 155,  25, 518])

In [52]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [54]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# The Where Function.

The **where** function performs a logical test and returns a given value if the test is True or another if the test is False
    
   **np.where(logical test,
                value if True,
                value if False)**


In [55]:
inventory_array = np.array([12,102,18,0,0])

inventory_array

array([ 12, 102,  18,   0,   0])

In [56]:
product_array1

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [57]:
np.where(inventory_array <= 0, 'Out of Stock', 'In Stock')

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [58]:
np.where(inventory_array <= 0,'Out of Stock',product_array1)

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [59]:
even_odd = np.arange(20)

even_odd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
np.where(even_odd % 2 == 0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [61]:
# Applying an exception to the clause that checks if the number is even or odd or 9 and returns the corresponding value.

np.where(even_odd % 2 == 0,'even',np.where(even_odd == 9,even_odd,'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

# Array Aggregation.

It lets you calculate metrics like sum, mean and max.


In [62]:
sales_array

array([[  25,   10,  155,   25,  518],
       [   0, 1827,  616,  317,  325]])

In [63]:
# Returns the sum of all the values in the array.

sales_array.sum()


3818

In [64]:
# Returns the average of the values in the array.

sales_array.mean()

381.8

In [65]:
# Returns the maximum value in the array.

sales_array.max()

1827

In [66]:
# Returns the minimum value in the array.

sales_array.min()

0

In [67]:
# By using the axis argument, the sum will aggregate across the rows

sales_array.sum(axis = 0)

array([  25, 1837,  771,  342,  843])

In [68]:
# Aggregates across columns

sales_array.sum(axis = 1)

array([ 733, 3085])

In [69]:
rng = np.random.default_rng(616)

price = (rng.random(10)*10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [70]:
inventory = rng.integers(0,100,10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43])

In [71]:
price.mean()

5.6

In [72]:
inventory.mean()

35.3

In [73]:
inventory.sum()

353

In [74]:
(price * inventory).sum()

1848.2900000000002

In [75]:
(price*inventory).argmax() # Returns the index of the most valued product.

0

In [76]:
price_2d = price.reshape(5,2)
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [77]:
price_2d.sum(axis = 0)

array([30.45, 25.55])

In [78]:
price_2d.sum(axis = 1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

# Array functions.

They let you perform other aggregations like median and percentiles.


In [79]:
sales_array

array([[  25,   10,  155,   25,  518],
       [   0, 1827,  616,  317,  325]])

In [80]:
np.median(sales_array) # Returns the median of the elements in the array.

236.0

In [81]:
np.percentile(sales_array,50)

236.0

In [82]:
np.unique(sales_array) # Returns only the unique values in an array

array([   0,   10,   25,  155,  317,  325,  518,  616, 1827])

In [83]:
np.sqrt(sales_array) # Returns the square roots of each element in the array

array([[ 5.        ,  3.16227766, 12.4498996 ,  5.        , 22.75961335],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

# Sorting arrays.

The sort() method will sort arrays in place.

Use the axis argument to specify which dimension to sort by.

In [84]:
sales_array.sort() # sorts along column axis by default
sales_array

array([[  10,   25,   25,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [85]:
sales_array.sort(axis = 0) # Sorts along the rows per column.
sales_array

array([[   0,   25,   25,  155,  518],
       [  10,  317,  325,  616, 1827]])

In [86]:
np.sort(sales_array)

array([[   0,   25,   25,  155,  518],
       [  10,  317,  325,  616, 1827]])

In [87]:
sales_array.reshape(10)

array([   0,   25,   25,  155,  518,   10,  317,  325,  616, 1827])

In [88]:
np.sort(sales_array)

array([[   0,   25,   25,  155,  518],
       [  10,  317,  325,  616, 1827]])

In [89]:
sales_array.sort()

sales_array.reshape(10)[::-1] # Slices the array from the last item hence returning a reversed sort.


array([1827,  616,  325,  317,   10,  518,  155,   25,   25,    0])

# Vectorization.

This is the process of pushong array operations into optimized C code, which is easier and more efficient than writing for loops.

Use vectorized operations whenever possible when manipulating data, and avoid writing for loops.

# Broadcasting.

Lets you perform vectorized operations with arrays of different sizes, where NumPy will expand the smaller array to fit the larger one.
* Single values(Scalars) can be broadcast into arrays of any dimension.



In [91]:
test_array = np.array([[1,2,3],[1,2,3],[1,2,3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [92]:
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

* Dimensions with a length greater than one must be the same size

In [93]:
test_array + np.array([3,2,1])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])