# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:


*   The number of dimensions
*   The shape
*   The number of elements in the array
*   The type of data contained inside


  
  
  

Package Imports

In [ ]:
import numpy as np

In [ ]:
my_list = [x * 10 for x in range(1, 11)]

array = np.array(my_list)

array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
array.ndim

1

In [ ]:
array.shape

(10,)

In [ ]:
array.size

10

In [ ]:
array.dtype

dtype('int64')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays.

Does NumPy have anything like the range() function from base Python?

If so:

* create the same array from assignment 1 using a NumPy function.
* Make it 5 rows and 2 columns.
* It's ok if the datatype is float or int.

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called random_array.

In [ ]:
my_array = np.linspace(10,100,10) #linspace is a numpy function for creating linear sequences out of the given range

my_array

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
my_array = np.arange(10,101,10) # aray method takes a start, stop and a step argument where the stop is non-inclusive
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
x = my_array.reshape(5,2)
x

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [18]:
rng = np.random.default_rng(2022)

random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data

Slice and index the random_array we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.
Thanks!

In [19]:
random_array[:2]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [24]:
random_array[:,0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [23]:
random_array[2,1]

0.04305584439252108